### ISSUE TITLE
Running Select (i.e. executeQuery) statements without using a DB readOnly session

### ISSUE THREAD

**Issue by uneewk** [scalikejdbc/scalikejdbc#1071]
I am using ScalikeJDBC 3.4.0 and snowflake-jdbc 3.11.0. ScalikeJDBC is wrapping the snowflake driver. I am running into an issue with both SQL interpolation and Query DSL with all Select statements. Inserts/Delete i.e. executeUpdate statements work. The reason for my issue it turns out is that ScalikeJDBC uses DB readOnly sessions for Select statements executeQuery but snowflake-jdbc driver does not support that. See [it here](https://github.com/snowflakedb/snowflake-jdbc/blob/3e2d1d931ef548f286b4a0bd76926a3c40c0f67d/src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java#L499). It explicitly throws an exception when ScalikeJDBC via dbcp tries to set the flag on the snowflake-jdbc driver. I have combed through the documentation and Google searches for a way around this with no success (i.e. tell ScalikeJDBC not to set that flag)

1. Can ScalikeJDBC provide a way to not set this on other JDBC drivers
2. Is there a workaround that I have not found? 

Thank you for you help. Greatly appreciated.

**Comment by seratch** [comment]
@uneewk Although I'm not an expert on Snowflake database and its JDBC driver, how about avoiding to use `DB.readOnly` for your use case? It's also possible to use a **not read-only** session for SELECT queries.

```scala
DB.autoCommit { implicit session => sql"....".map(...).list.apply() }
DB.localTx { implicit session => sql"....".map(...).list.apply() }
```

**Comment by uneewk** [comment]
@seratch Indeed that works. Thank You.

**Comment by uneewk** [comment]
@seratch using the solution you suggested is working beautifully. However, using QueryDSL doesn't work because of the same problem i.e. when ScalikeJDBC retrieves column names for matched tables, it does so with readonly session block but the Snowflake JDBC driver does not support setting readonly session to true. Is there any way I can workaround this i.e. to use QueryDSL and at the same time make ScalikeJDBC avoid attempting to set readonly session on the underlying driver? I mean to close this issue just reopening here to keep the history.

**Comment by seratch** [comment]
@uneewk 
>Is there any way I can workaround this i.e. to use QueryDSL and at the same time make ScalikeJDBC avoid attempting to set readonly session on the underlying driver?

At this moment, the only workaround would be overriding `columnNames` in your `SQLSyntaxSupport` classes/objects. This means you need to manually list all the columns. But it works for sure and if the field is not empty, ScalikeJDBC never issues a query for it.

**Comment by uneewk** [comment]
Thank you. I will try this and report back.

**Comment by okennedy** [comment]
The same problem appears in SQLite (https://github.com/xerial/sqlite-jdbc/issues/247), where setReadOnly also triggers an exception.  This actually seems like correct behaviour on their part, since transparently ignoring concurrency directives seems like a recipe for trouble.  Given how extensively `readOnly` appears throughout the scalikejdbc internals, would it be possible to add a flag on the ConnectionPool (or similar) that allows users to manually request that `readOnly` be transparently replaced with a read/write transaction mode?

**Comment by seratch** [comment]
If the behavior is JTA compatible, `jtaDataSourceCompatible` should work for you.

```scala
GlobalSettings.jtaDataSourceCompatible = true
```

* https://github.com/scalikejdbc/scalikejdbc/blob/535eb553bec5a951c33e3463e7054c5e4d1ea1b3/scalikejdbc-core/src/main/scala/scalikejdbc/Tx.scala#L37-L39
* https://github.com/scalikejdbc/scalikejdbc/issues/1061#issuecomment-562015525
* https://github.com/scalikejdbc/scalikejdbc/issues/988#issuecomment-475805617

**Comment by okennedy** [comment]
Seems a bit like overkill... I'm not sure it's a great idea to take over transaction management entirely.

The (hopefully temporary) workaround I came up with is to create a shim between `SQLiteConnection` and scalikejdbc that silently drops setReadOnly (i.e., all transactions are treated as read/write).  It'd be nice to have this as a configurable parameter in either the SQLite driver or scalikejdbc, but it turned out to be a relatively painless fix.

**Comment by seratch** [comment]
@uneewk 's issue is already resolved here. Let me close this issue now. For @okennedy's issue, I've created #1169 for tracking the progress.
