### ISSUE TITLE
fix `DBConnection#getTable`

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc#2258]
`getTable` and internal `_getTable` return type is `Option` because call `tableList.headOption` in here.

https://github.com/scalikejdbc/scalikejdbc/blob/190781d5e56756d18160b9a3163ca0ea4eb25fec/scalikejdbc-core/src/main/scala/scalikejdbc/DBConnection.scala#L545

But this cause some problems if there are same table in different databases (in MySQL in my env).

I think we should change `getTable` method.

1. return `Seq` instead `Option` with `catalog` information?

change current `getTable` method or add another new method?

```diff
-  ): Option[Table] = {
+  ): Seq[Table] = {
     val tableList =
       new ResultSetIterator(meta.getTables(null, schema, table, tableTypes))
         .map { rs =>
           (
+            rs.string("TABLE_CAT"),
             rs.string("TABLE_SCHEM"),
             rs.string("TABLE_NAME"),
             rs.string("REMARKS")
@@ -542,13 +543,14 @@ trait DBConnection extends LogSupport with LoanPattern with AutoCloseable {
         }
         .to(LazyList)
 
-    tableList.headOption.map { case (schema, table, remarks) =>
+    tableList.map { case (catalog, schema, table, remarks) =>
       val pkNames: List[String] = new ResultSetIterator(
         meta.getPrimaryKeys(null, schema, table)
       ).map(_.string("COLUMN_NAME")).toList
 
       Table(
         name = table,
+        catalog = catalog,
```

2. add `catalog` param?

https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getTables-java.lang.String-java.lang.String-java.lang.String-java.lang.String:A-

```diff
     meta: DatabaseMetaData,
     schema: String,
     table: String,
+    catalog: String,
     tableTypes: Array[String] = DBConnection.tableTypes
   ): Option[Table] = {
     val tableList =
-      new ResultSetIterator(meta.getTables(null, schema, table, tableTypes))
+      new ResultSetIterator(meta.getTables(catalog, schema, table, tableTypes))
         .map { rs =>
```

3. any other solutions? 🤔

**Comment by seratch** [comment]
I am aware that newer MySQL drivers can behave quite differently than other drivers. Usually `DatabaseMetaData.getTables(...)` does not return multiple rows, and that's why the code use headOption to extract the data. If the latest MySQL driver can return a few rows and we need to merge the data into one to identify catalog, etc., option 1 could be a solution for the use case. Regarding option 2, I have no objections to the change. I myself don't have the bandwidth for the enhancement work. Pull requests with great quality would be appreciated.

**Comment by xuwei-k** [comment]
- https://github.com/scalikejdbc/scalikejdbc/pull/2259
