### ISSUE TITLE
column named to_string

### ISSUE THREAD

**Issue by tculshaw** [scalikejdbc/scalikejdbc#389]
Crazy, but true. I'm using a pre-generated schema and usingh the reverse engineering scalikejdbcGenAll task.

The code generates foine, but won't compile due to 'toString' being essentially a reserved (function) name.

I noticed in the generator code there's a columnNameToFieldName attribute and also digging deeper, there's a GeneratorConfig.reservedWords which I would like to append to.

Is there a way I can configure 'toString' as reserved in build.sbt or Build.scala?

**Comment by seratch** [comment]
`GeneratorConfig.reservedWords` was introduced by @xuwei-k a few days ago. So it will be available since next version (2.2.5, release date has not yet been decided). 

If you don't mind modifying the generated code, using `nameConverters` instead of quoted field names can help you. (e.g. `override val nameConverters = Map("^toStr$" -> "to_string")`)
http://scalikejdbc.org/documentation/sql-interpolation.html

**Comment by tculshaw** [comment]
That'll do for now - thanks for the quick reply!

**Comment by seratch** [comment]
Thank you for using ScalikeJDBC! Let me close this issue now.
