### ISSUE TITLE
Can only use a.result.column("name") instead of using a.result.name

### ISSUE THREAD

**Issue by zhaohangbo** [scalikejdbc/scalikejdbc#570]
![image](https://cloud.githubusercontent.com/assets/12908906/19228742/9fe47bb6-8efa-11e6-879e-a9657ba58b92.png)

![image](https://cloud.githubusercontent.com/assets/12908906/19229010/e2bfe69e-8efc-11e6-8605-a09584e05f36.png)

field `name` is usually a common filed for many models 
But I can only use a.result.column("name") instead of using a.result.name
Because it's a internal field of `case class ResultSQLSyntaxProvider`

I think this is a bug need to be fixed

**Comment by seratch** [comment]
I've recognized it is an issue for many cases for months. I was planning to break API compatibilities to fix this issue since 3.0 but it may be reasonable to change since 2.5. The reason for that is that most users don't use `result.name`. If there is no strong objection, it's ok for me to fix this since 2.5.
