### ISSUE TITLE
CallableStatement support

### ISSUE THREAD

**Issue by seratch** [scalikejdbc/scalikejdbc#59]
http://docs.oracle.com/javase/7/docs/api/java/sql/CallableStatement.html
http://www.herongyang.com/JDBC/MySQL-CallableStatement-Procedure-Multiple-Queries.html
http://www.herongyang.com/JDBC/MySQL-CallableStatement-Multiple-ResulSet.html
## Draft API design:

TODO

``` scala
val result = DB autoCommit { session => 
  session.procedure("CALL HeadTail(?)") { proc: Procedure => 
    proc.outType(1, SQLTypes.INTEGER)
    // #getMoreResults and then #getResultSet as a traversable
    val results1 = proc.nextResultSet.map { rs => rs.int("id") }
    val results2 = proc.nextResultSet.map { rs => rs.int("id") }
    val i = proc.int(1)
    Result(i, results1, results2)
  }
}
```

**Comment by naskoboy** [comment]
Hi seratch,

I have been big fan of Querulous and was very excited when I came across your scalikejdbc.
I think I can use it in my projects. However I need somehow to call oracle stored functions having this signature
MyFunc(d1: datetime, d2: datetime) returns VARCHAR2

I tried following but it didn't work since I am not allowed to do DMLs in selected function:
sql"select test_etl_days($d1, $d2) value FROM dual".map(_.string("value")).map(_.string(1)).single().apply().get

Pls advise how I can do this with scalikejdbc ?
Or (if it's not much trouble for you) to have it implemented as new feature.

Thanks a lot.
