### ISSUE TITLE
Custom JDBC data source properties

### ISSUE THREAD

**Issue by tejasmanohar** [scalikejdbc/scalikejdbc#656]
Is it possible to add custom JDBC data source properties? I'm trying to do something like

```java
Properties info = new Properties();
info.put("...", "...")
info.put("s3_staging_dir", "s3://S3 Bucket Location/");

Class.forName("com.amazonaws.athena.jdbc.AthenaDriver");

Connection connection = DriverManager.getConnection("jdbc:awsathena://athena.us-east-1.amazonaws.com:443/", info);
```

**Comment by tejasmanohar** [comment]
Nevermind, I think I can just add these to the URI. That said, would you be open to adding properties (with empty default) to the ConnetionPoolSettings? I can PR.

**Comment by seratch** [comment]
Interesting! >using ScalikeJDBC for Athena

I don't see the necessity to support `Properties` in `ConnectionPoolSettings` because the value is needed only for `DriverManager`. In the case, using `DataSourceConnectionPool` + some `DataSource` adapter would be natural.

- Spring's DriverManagerDataSource: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/datasource/DriverManagerDataSource.html
- `DataSourceConnectionPool` example: http://scalikejdbc.org/documentation/connection-pool.html#hikaricp

**Comment by tejasmanohar** [comment]
To clarify, do you recommend supplying a HikariCP pool to ScalalikeJDBC? I used that before for Athena in Java so that should work.

**Comment by seratch** [comment]
@tejasmanohar Both are fine with me.  Spring's `DriverManagerDataSource` is also simple. I've never tried yet but doing as below should work:

```scala
val dataSource = DriverManagerDataSource(url, props)
ConnectionPool.singleton(new DataSourceConnectionPool(dataSource))
 ```

Since you've already figured out how to use HikariCP for Athena, I think using HikariCP would be smooth, though.

**Comment by tejasmanohar** [comment]
oh cool! i'll try that out, too. thanks

**Comment by tejasmanohar** [comment]
One question though, is it possible to make a singleton out of ConnectionPool that uses DataSourceConnectionPool _and_ ConnectionPoolSettings (latter is for max conns and whatnot)

**Comment by tejasmanohar** [comment]
nevermind! that's redundant
